# Generated by Django 5.0.1 on 2024-01-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdfconvert', '0003_remove_education_profile_remove_language_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
